### ISSUE TITLE
[crash] TypeError: Cannot read property ‘get_transaction’ of null

### ISSUE THREAD

**Issue by GiedriusM** [8devices/node-red-contrib-lesley#4]
Oct 25 14:11:51 raspberrypi sudo[24981]: pam_unix(sudo:session): session closed for user root
Oct 25 14:11:51 raspberrypi sudo[24990]:       pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/local/bin/wpanctl status
Oct 25 14:11:51 raspberrypi sudo[24990]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 25 14:11:51 raspberrypi sudo[24990]: pam_unix(sudo:session): session closed for user root
Oct 25 14:11:51 raspberrypi Node-RED[24180]: 25 Oct 14:11:51 - [red] Uncaught Exception:
Oct 25 14:11:51 raspberrypi Node-RED[24180]: 25 Oct 14:11:51 - TypeError: Cannot read property ‘get_transaction’ of null
Oct 25 14:11:51 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 14:11:51 raspberrypi systemd[1]: nodered.service: Unit entered failed state.
Oct 25 14:11:51 raspberrypi systemd[1]: nodered.service: Failed with result ‘exit-code’.
Oct 25 14:11:51 raspberrypi systemd[1]: nodered.service: Service hold-off time over, scheduling restart.
Oct 25 14:11:51 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool..
Oct 25 14:11:51 raspberrypi systemd[1]: Started Node-RED graphical event wiring tool..

**Comment by GiedriusM** [comment]
Oct 26 12:58:31 raspberrypi Node-RED[2745]: 26 Oct 12:58:31 - [red] Uncaught Exception:
Oct 26 12:58:31 raspberrypi Node-RED[2745]: 26 Oct 12:58:31 - TypeError: Cannot read property 'get_transaction' of null
Oct 26 12:58:31 raspberrypi Node-RED[2745]:     at Timeout.SensorNode.node.interval_id.setInterval [as _onTimeout] (/lib/node_modules/node-red-contrib-lesley/nodes/sensor4400_service.js:19:19)
Oct 26 12:58:31 raspberrypi Node-RED[2745]:     at ontimeout (timers.js:386:14)
Oct 26 12:58:31 raspberrypi Node-RED[2745]:     at tryOnTimeout (timers.js:250:5)
Oct 26 12:58:31 raspberrypi Node-RED[2745]:     at Timer.listOnTimeout (timers.js:214:5)
Oct 26 12:58:31 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE

**Comment by GiedriusM** [comment]
NodeRed lūžta kai yra nesukonfigūruotas node, o konkrečiau jo service. Tuomet node.service būna null ir kai timeris kviečia node.service.get_transaction - crash.

**Comment by GiedriusM** [comment]
Not reproducible, stale issue. Closing.
